name: my first action file
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: list and read file
        run: |
          echo "welcome to my first yml file"
          ls -ltra
          cat README.md

      - name: Generate ASCII artwork
        run: cowsay -f dragon "Run for cover, I am DRAGON... RAWR" >> dragon.txt
        
      #- name: list files
      #  run: ls
      #- name: read file
      #  run: cat README.md

        