name: generate ascii 
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am DRAGON... RAWR" >> dragon.txt
    
      - name: Read file
        run: cat dargon.txt

      - name: list the files
        run: ls -ltra

        
      #- name: list files
      #  run: ls
      #- name: read file
      #  run: cat README.md

        