name: generate ascii using script
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: list the files
        run: ls -ltra

      - name: Execute commands from script
        run: ./ascii-script.sh
      

        
      #- name: list files
      #  run: ls
      #- name: read file
      #  run: cat README.md

        